# Stock Portfolio Tracker Configuration
# This file contains all configurable settings for the portfolio tracker

# Application Information is defined in conf/constants.py

# File Paths Configuration
paths:
  portfolios_dir: "/Users/royarzab/chief_plugins/stocks/portfolios"  # Directory containing portfolio YAML files
  config_file: "conf/config.yaml"   # This configuration file
  log_file: "logs/portfolio.log"    # Log file path (optional)

# Display Configuration
display:
  terminal_width: 120             # Default terminal width
  borders: false                  # Default border setting for tables
  show_totals: true               # Show totals row by default
  include_crypto: false           # Include crypto by default
  max_description_length: 28      # Maximum characters for company descriptions
  stretch_to_terminal: true       # Stretch tables to full terminal width (true) or respect terminal_width (false)
  
  # Sorting Configuration
  default_sort_column: "symbol"   # Default column to sort by
  default_sort_descending: false  # Default sort order (false = ascending, true = descending)
  
  # Available sort columns (for reference and validation)
  available_sort_columns:
    - "portfolio"      # Portfolio name
    - "symbol"         # Stock symbol
    - "description"    # Company description
    - "qty"            # Quantity/shares
    - "ave"            # Average cost (or day cost in day mode)
    - "price"          # Current price
    - "gain_pct"       # Gain percentage
    - "cost"           # Total cost
    - "gain_dollars"   # Gain in dollars
    - "value"          # Current value

# Currency Formatting
currency:
  decimal_places: 2               # Number of decimal places for currency
  show_symbol: true               # Show $ symbol
  colored_mode: true              # Use colors for positive/negative values
  negative_format: "parentheses"  # Format for negative values: "parentheses" or "minus"

# Table Display Options
tables:
  bordered_style: "heavy"         # Border style for -b flag: "light", "heavy", "double"
  columnar_style: "clean"         # Style for columnar display: "clean", "minimal"
  header_style: "bold"            # Header text style: "bold", "italic", "normal"
  number_alignment: "right"       # Number column alignment: "left", "right", "center"

# API Configuration
api:
  yahoo:
    timeout: 30                   # Request timeout in seconds
    retries: 3                    # Number of retries on failure
    cache_duration: 3600          # Cache duration in seconds (1 hour)

# Debug Configuration
debug:
  enabled: false                  # Enable debug output
  show_cache_status: false        # Show cache loading/saving messages
  show_spinner_debug: false       # Show spinner debug messages
  

# Portfolio Configuration
portfolio:
  default_currency: "USD"         # Default currency for calculations
  lot_date_format: "%Y-%m-%d"     # Date format for lot dates
  auto_detect_crypto: true        # Automatically detect crypto symbols
  crypto_symbols:                 # Known crypto symbols
    - "BTC-USD"
    - "ETH-USD"
    - "DOGE-USD"
    - "LTC-USD"
    - "XRP-USD"
    - "MATIC-USD"
    - "XLM-USD"
    - "SHIB-USD"
    - "TEL-USD"

# Logging Configuration
logging:
  level: "INFO"                   # Log level: DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: false             # Enable file logging
  console_logging: true           # Enable console logging
