# TradeTrack Configuration Template
# Copy this file to conf/config.yaml and customize it

# Stock Portfolio Tracker Configuration
# This file contains all configurable settings for the portfolio tracker

# File Paths Configuration
paths:
  portfolios_dir: "portfolios"  # Directory containing portfolio YAML files
  log_file: "logs/portfolio.log"    # Log file path (optional)

# Display Configuration
display:
  terminal_width: 120             # Default terminal width
  borders: false                  # Default border setting for tables
  show_totals: true               # Show totals row by default
  include_crypto: false           # Include crypto by default
  max_description_length: 28      # Maximum characters for company descriptions
  stretch_to_terminal: false      # Stretch tables to full terminal width (true) or respect terminal_width (false)
  
  # Sorting Configuration
  default_sort_column: "symbol"   # Default column to sort by
  default_sort_descending: false  # Default sort order (false = ascending, true = descending)
  
  # Available sort columns (for reference and validation)
  available_sort_columns:
    - "portfolio"      # Portfolio name
    - "symbol"         # Stock symbol
    - "description"    # Company description
    - "qty"            # Quantity/shares
    - "ave"            # Average cost (or day cost in day mode)
    - "price"          # Current price
    - "gain_pct"       # Gain percentage
    - "cost"           # Total cost
    - "gain_dollars"   # Gain in dollars
    - "value"          # Current value

# Currency Formatting
currency:
  decimal_places: 2               # Number of decimal places for currency
  show_symbol: true               # Show $ symbol
  colored_mode: true              # Use colors for positive/negative values
  negative_format: "parentheses"  # Format for negative values: "parentheses" or "minus"

# Table Display Options
tables:
  bordered_style: "heavy"         # Border style for -b flag: "light", "heavy", "double"
  columnar_style: "clean"         # Style for columnar display
  header_style: "bold"            # Header text style
  number_alignment: "right"       # Number alignment: "left", "center", "right"

# API Configuration
api:
  yahoo:
    timeout: 30                   # Request timeout in seconds
    retries: 3                    # Number of retry attempts
    cache_duration: 300           # Cache duration in seconds (5 minutes)
  td_ameritrade:
    enabled: false                # Enable TD Ameritrade API (not implemented)
    client_id: ""                 # TD Ameritrade client ID
    redirect_uri: ""              # TD Ameritrade redirect URI

# Note: Crypto symbols are automatically detected at runtime
# No need to configure them manually in most cases
