# GitHub Pages Configuration for TradeTrack
# Theme: Dinky (GitHub supported theme)

title: TradeTrack
description: A modern CLI stock portfolio tracker with real-time data and beautiful displays
url: https://randyoyarzabal.github.io
baseurl: /tradetrack

# Site settings
logo: /tradetrack/assets/images/logo.png
favicon: /tradetrack/assets/images/favicon.ico

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/randyoyarzabal/tradetrack

# Footer
footer_content: "TradeTrack - Track your investments with confidence"

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "//github.com/randyoyarzabal/tradetrack"

remote_theme: pages-themes/slate@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
